import activity1Diagram from '../../../assets/ladder-diagrams/activity-2.png';
import type { ActivityAnswerDefinition } from './types';

export const activity2Answer: ActivityAnswerDefinition = {
  routeId: '2',
  title: 'Start-Stop Latching Conrtol Unit',
  diagram: activity1Diagram,
  rule: {
    requiredInputDevices: { button: 1 },
    requiredOutputDevices: { relayModule: 1, lightIndicator: 1 },
    requiredComponents: { battery: 1, relayModule: 1, lightIndicator: 1 },
    minWires: 7,
    customConnections: [
      ['lights_5', 'lights1_1'],
      [
        ['lights_1', 'vminus_1'],
        ['lights_1', 'vminus_2'],
        ['lights_1', 'vminus_3'],
        ['lights_1', 'vminus_4'],
        ['lights_1', 'vminus_5'],
        ['lights_1', 'vminus_6'],
        ['lights_1', 'vminus_7'],
        ['lights_1', 'vminus_8'],
        ['lights_1', 'vminus_9'],
        ['lights_1', 'vminus_10'],
        ['lights_1', 'vminus_11'],
        ['lights_1', 'vminus_12'],
      ],
      [
        ['relay1_2', 'vminus_1'],
        ['relay1_2', 'vminus_2'],
        ['relay1_2', 'vminus_3'],
        ['relay1_2', 'vminus_4'],
        ['relay1_2', 'vminus_5'],
        ['relay1_2', 'vminus_6'],
        ['relay1_2', 'vminus_7'],
        ['relay1_2', 'vminus_8'],
        ['relay1_2', 'vminus_9'],
        ['relay1_2', 'vminus_10'],
        ['relay1_2', 'vminus_11'],
        ['relay1_2', 'vminus_12'],
      ],
      [
        ['relay1_9', 'vplus_1'],
        ['relay1_9', 'vplus_2'],
        ['relay1_9', 'vplus_3'],
        ['relay1_9', 'vplus_4'],
        ['relay1_9', 'vplus_5'],
        ['relay1_9', 'vplus_6'],
        ['relay1_9', 'vplus_7'],
        ['relay1_9', 'vplus_8'],
        ['relay1_9', 'vplus_9'],
        ['relay1_9', 'vplus_10'],
        ['relay1_9', 'vplus_11'],
        ['relay1_9', 'vplus_12'],
      ],
      [
        ['relay1_10', 'vplus_1'],
        ['relay1_10', 'vplus_2'],
        ['relay1_10', 'vplus_3'],
        ['relay1_10', 'vplus_4'],
        ['relay1_10', 'vplus_5'],
        ['relay1_10', 'vplus_6'],
        ['relay1_10', 'vplus_7'],
        ['relay1_10', 'vplus_8'],
        ['relay1_10', 'vplus_9'],
        ['relay1_10', 'vplus_10'],
        ['relay1_10', 'vplus_11'],
        ['relay1_10', 'vplus_12'],
      ],
      ['lights_2', 'relay1_7'],
      ['lights_6', 'relay1_4'],
      ['relay1_6', 'counter_4'],
      [
        ['counter_3', 'vplus_1'],
        ['counter_3', 'vplus_2'],
        ['counter_3', 'vplus_3'],
        ['counter_3', 'vplus_4'],
        ['counter_3', 'vplus_5'],
        ['counter_3', 'vplus_6'],
        ['counter_3', 'vplus_7'],
        ['counter_3', 'vplus_8'],
        ['counter_3', 'vplus_9'],
        ['counter_3', 'vplus_10'],
        ['counter_3', 'vplus_11'],
        ['counter_3', 'vplus_12'],
      ],
      ['counter_4', 'counter_5'],
      [
        ['counter_6', 'vminus_1'],
        ['counter_6', 'vminus_2'],
        ['counter_6', 'vminus_3'],
        ['counter_6', 'vminus_4'],
        ['counter_6', 'vminus_5'],
        ['counter_6', 'vminus_6'],
        ['counter_6', 'vminus_7'],
        ['counter_6', 'vminus_8'],
        ['counter_6', 'vminus_9'],
        ['counter_6', 'vminus_10'],
        ['counter_6', 'vminus_11'],
        ['counter_6', 'vminus_12'],
      ],
    ],
  },
};
